version: "3.8"
services:
  map-recommendation-redis:
    container_name: map-recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: tkaqkeldk/map-recommendation-redis
    ports:
      - "6379:6379"
  map-recommendation-database:
    container_name: map-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: tkaqkeldk/map-recommendation-database
    environment:
      - MARIADB_DATABASE=map-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"