


spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common

kakao:
  rest:
    api:
      key: ${KAKAO-REST-API-KEY}

# ...

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/restaurant-recommendation?allowPublicKeyRetrieval=true&useSSL=false
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    properties:
      hibernate:
        id.new_generator_mappings: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

map:
  recommendation:
    base:
      url: http://localhost:8080/dir/

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://map-recommendation-database:3306/map-recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: map-recommendation-redis
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate # prod 배포시 validate
    show-sql: true

map:
  recommendation:
    base:
      url: http://localhost/dir/ # aws ec2 ip 할당 받은 후 변경 예정

