


spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ap-northeast-2

kakao:
  rest:
    api:
      key: ${KAKAO-REST-API-KEY}

jwt:
  expiration: 86400000 # 1 day

# ...

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/map-recommendation?allowPublicKeyRetrieval=true&useSSL=false
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  redis:
    host: localhost
    port: 6379

  jpa:
    properties:
      hibernate:
        id.new_generator_mappings: false
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  # documentationPluginsBootstrapper 대응
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true

map:
  recommendation:
    base:
      url: http://localhost:8080/dir/

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ap-northeast-2

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://map-recommendation-database:3306/map-recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  redis:
    host: map-recommendation-redis
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create # prod 배포시 validate
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


map:
  recommendation:
    base:
      url: http://localhost/dir/ # aws ec2 ip 할당 받은 후 변경 예정